src/Entity/Article.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message = "Un article avec ce nom existe déjà ! Dommage"
 * )
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     * min = 10,
     * max = 255,
     * minMessage = "Le titre doit faire plus de 10 caracteres !",
     * maxMessage = "Le titre ne doit pas faire plus de 255 caracteres !"
     *  )
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $short_description;

    /**
     * @ORM\Column(type="text")
     */
    private $detailed_description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="article")
     * @Assert\Valid()
     */
    private $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     */
    public function initializeSlug(){
        if( empty($this->slug) ){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getDetailedDescription(): ?string
    {
        return $this->detailed_description;
    }

    public function setDetailedDescription(string $detailed_description): self
    {
        $this->detailed_description = $detailed_description;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setArticle($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getArticle() === $this) {
                $image->setArticle(null);
            }
        }

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Ad;
use App\Form\ImageType;
use Doctrine\DBAL\Types\FloatType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class ArticleType extends AbstractType
{
    private function getConfiguration($label, $placeholder, $options = []){
        return(array_merge([
            'label' => $label,
            'attr' => [
                'placeholder' => $placeholder
            ]
            ], $options));
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration('Titre', "Tapez un super titre pour votre annonce"))
            ->add('slug', TextType::class, $this->getConfiguration('Chaine URL', "Adresse web (Automatique)", ['required' => false]))
            ->add('price', MoneyType::class, $this->getConfiguration("Prix par nuit", "Indiquez le prix que vous voulez pour une nuit"))
            ->add('short_description', TextType::class, $this->getConfiguration("Introduction", "Donnez une description globale de l'annonce"))
            ->add('detailed_description', TextareaType::class, $this->getConfiguration("Description", "Tapez une description qui donne..."))
            ->add('coverImage', UrlType::class, $this->getConfiguration("Url de l'image", "Donnez l'adresse de votre image"))
            ->add(
                'images',
                CollectionType::class,
                [
                    'entry_type' => ImageType::class,
                    'allow_add' => true,
                    'allow_delete' => true
                ]
            )
            ->add('save', SubmitType::class,[
                'label' => "Ajouter un nouvel article",
                'attr' => [
                    'class' => "btn btn-primary"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Entity\Commentaire;
use App\Form\CommentaireType;
use App\Repository\ArticleRepository;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ArticleController extends AbstractController
{
    /**
     * @Route("/article/new", name="article_create")
     */
    public function create(Request $request, ObjectManager $manager)
    {
        $article = new Article();

        $form = $this->createForm(ArticleType::class, $article);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){

            foreach($article->getImages() as $image){
                $image->setArticle($article);
                $manager->persist($image);
            }

            $manager->persist($article);
            $manager->flush();

            $this->addFlash('success', "L'article <strong>{$article->getTitle()}</strong> a bien été enregistré");

            return $this->redirectToRoute('article_show', [
                'slug' => $article->getSlug()
            ]);
        }

        return $this->render('article/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/article/{slug}/edit", name="article_edit")
     * 
     * @return Response
     */
    public function edit(Article $article, Request $request, ObjectManager $manager)
    {
        $form = $this->createForm(ArticleType::class, $article);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){

            foreach($article->getImages() as $image){
                $image->setArticle($article);
                $manager->persist($image);
            }

            $manager->persist($article);
            $manager->flush();

            $this->addFlash('success', "L'article <strong>{$article->getTitle()}</strong> a bien été enregistré");

            return $this->redirectToRoute('article_show', [
                'slug' => $article->getSlug()
            ]);
        }

        return $this->render('article/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/article/{page?1}", name="article_index")
     */
    public function index(ArticleRepository $repo, $page)
    {
        $limit = 6;

        $start = $page * $limit - $limit;

        $total = count($repo->findAll());

        $pages = ceil($total / $limit);
        
        return $this->render('article/index.html.twig', [
            'paginate' => $pages,
            'articles' => $repo->findBy([], [], $limit, $start),
            'page' => $page
        ]);
    }

    /**
     * @Route("/article/show/{slug}", name="article_show")
     */
    public function show( Article $article )
    {
        #$ad = $repo->findOneBySlug($slug);
        return $this->render('article/show.html.twig', [
            'article' => $article
        ]);
    }
}

templates/article/_collection.html.twig
{% block _article_images_widget %}
    <p>Ici, vous pouvez ajoutez vos propres images</p>
    {{ form_widget(form) }}

    <input type="hidden" id="widgets-counter" value="0">

    <div class="form-group">	
        <button type="button" class="btn btn-primary" id="add-image">Ajouter une image</button>
    </div>
{% endblock %}

{% block _article_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block _article_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-18">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button data-action='delete' data-target="#block_{{ id }}" type="button" class="btn btn-danger">X</button>
            </div>
        </div>  
    </div>
{% endblock %}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'article/_collection.html.twig' %}

{% block title %}Edition d'un article{% endblock %}

{% block body %} 
    <div class="container">
        <h1>Modifier l'article</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/js/ad.js"></script>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos articles{% endblock %}

{% block body %}
    <div class="container">
    <h1 class="my-3">Voici tous les articles disponibles</h1>
    <div class="row">
        {% for article in articles %}
            <div class="col-md-4">
                <div class="card bg-light mb-3">
                    <div class="card-header text-center">
                        <strong>{{ article.price }}&euro;</strong>
                        <br>
                        <small>Pas encore noté</small>
                    </div>

                    <img src="{{ article.coverImage }}" alt="Image de l'appartement" style="height: 200px; width: 100%; display: block">

                    <div class="card-body">
                        <h4 class="card-title">{{ article.title }}</h4>
                        <p class="card-text">
                            {{ article.shortDescription }}
                        </p>
                        <div class="text-center">
                            <a href="{{ path('article_show', {'slug': article.slug } )}}" class="btn btn-secondary">En savoir plus</a>
                        </div>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>

    <div class="d-flex justify-content-center mt-5">
        <ul class="pagination">
            <li class="page-item {% if page == 1 %}disabled{% endif %}">
                <a class="page-link" href="{{ path("article_index", {'page': page - 1 }) }}">&laquo;</a>
            </li>

            {% for i in 1..paginate %}
                <li class="page-item {% if page == i %}active{% endif %}">
                    <a class="page-link" href="{{ path("article_index", {'page': i}) }}">{{ i }}</a>
                </li>
            {% endfor %}

            <li class="page-item {% if page == paginate %}disabled{% endif %}">
                <a class="page-link" href="{{ path("article_index", {'page': page + 1 }) }}">&raquo;</a>
            </li>
        </ul>
    </div>

    </div>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% form_theme form "article/_collection.html.twig" %}

{% block title %}Creation d'un article{% endblock %}

{% block body %}
    <div class="container">
        <h1>Créer un nouvel article</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $('#add-image').click(function(){
            const index = +$('#widgets-counter').val();

            const tmpl = $('#article_images').data('prototype').replace(/__name__/g, index);

            $('#article_images').append(tmpl);

            $("#widgets-counter").val(index + 1);

            handleDeleteButtons();
        })

        function handleDeleteButtons(){
            // Au click sur le bouton avec l'attribut data-action="delete"
            $('button[data-action="delete"]').click(function(){

                // On récupére la cible contenu dans l'attribut data-target
                const target = this.dataset.target;

                // On supprime la cible
                $(target).remove();

            })
        }
        handleDeleteButtons();   
    </script>
{% endblock %}

templates/article/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block body %}
<div class="container">
    <div class="ad-title-sym" style="background-image: url({{ article.coverImage }})">
        <div class="container">
            <h1>{{ article.title }}</h1>
            <p>{{ article.shortDescription }}</p>
            <p class="h2">
                <strong>{{ article.price }}&euro;</strong>
            </p>
            <a class="btn btn-primary" href="#">Acheter</a>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ article.detailedDescription | raw }}

                <div class="carousel slide" data-ride="carousel" id="carouselExampleIndicators">
                    <ol class="carousel-indicators">
                        {% for image in article.images %}
                            <li class="{% if loop.first %}active{% endif %}" data-slide-to="{{ loop.index0 }}" data-target="#carouselExampleIndicators"></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in article.images %}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img alt="..." class="d-block w-100" src="{{ image.url }}">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ article.title }}</h5>
                                    <p>{{ image.caption }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" data-slide="prev" href="#carouselExampleIndicators" role="button">
                        <span aria-hidden="true" class="carousel-control-prev-icon"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" data-slide="next" href="#carouselExampleIndicators" role="button">
                        <span aria-hidden="true" class="carousel-control-next-icon"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            {# <div class="col">
                <div class="row">
                    <div class="col-4">
                        <img alt="Avatar de Joseph" src="http://placehold.it/64x64"></div>
                    <div class="col">
                        <h3>Joseph Dupont</h3>
                        <span class="badge badge-primary">3 annonces</span>
                    </div>
                </div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure nisi in vel suscipit, aliquid iusto enim cumque neque excepturi pariatur?</p>
                <p>Ducimus tempora animi accusamus error libero quam impedit et. Cum atque hic rerum dolore voluptas officiis expedita nulla. Rerum, dignissimos.</p>
                <p>Alias fugiat tempore, fugit aut quisquam facilis temporibus, omnis, praesentium architecto molestias quod reiciendis unde possimus vel cum rem laboriosam.</p>
            </div> #}
        </div>
    </div>
</div>

{% endblock %}